In [3]:
import matplotlib as plt
import numpy as np
import pandas as pd
%matplotlib inline

1.2.1 Пример

In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


1.2.2 Пример

In [ ]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


1.2.3 Пример

In [ ]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.005873169107519005 0.9976002102518221 0.5488788551287622


1.2.4 Пример

In [ ]:
A = np.arange(25).reshape(5, 5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


1.2.5 Пример

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


1.2.6 Пример

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


1.3.1 Задание

Задача:
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [ ]:
matrix = np.zeros((8,8), dtype=np.int32)
matrix[1::2,::2], matrix[::2,1::2] = 1, 1
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

1.3.2 Задание

Задача:
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange

In [ ]:
matrix = np.matrix([np.arange(5) for i in range(5)])
matrix

matrix([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

1.3.3 Задание

Задача:
Создать массив 3x3x3 со случайными значениями.

In [ ]:
matrix = np.random.random((3, 3, 3))
matrix

array([[[0.40711874, 0.29078021, 0.61559679],
        [0.97850681, 0.37798245, 0.18905828],
        [0.24508759, 0.05704977, 0.80138605]],

       [[0.46176169, 0.58173386, 0.07251747],
        [0.59424692, 0.48279597, 0.7748655 ],
        [0.55927772, 0.86198185, 0.15359378]],

       [[0.33827359, 0.07902492, 0.06113022],
        [0.81369537, 0.48937322, 0.040501  ],
        [0.80459166, 0.63901598, 0.06521713]]])

1.3.4 Задание

Задача:
Создать матрицу с 0 внутри, и 1 на границах.

In [ ]:
matrix = np.ones((5,5), dtype=np.int32)
matrix[1:len(matrix)-1, 1:len(matrix)-1] = 0
matrix

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

1.3.5 Задание

Задача:
Создайте массив и отсортируйте его по убыванию.


In [ ]:
array = np.random.randint(-10000,10000,128)
print("unsorted: ", array)
print("sorted: ", end="")
-np.sort(array)

unsorted:  [ -694 -8766  8426    85 -4481 -1067  3790  2878  2820  3991 -9443  8987
 -4013 -7071  7505  9651 -9600  8477 -8560 -2994  4466 -7606 -8579  2443
  9414 -7689  8302  -739  2006  3883  8052  7359 -5661  4611  6089 -9823
 -4107  8031 -7099 -1019  2806 -4871 -1646 -4333 -1012 -8844  2753  3886
 -1872  3783  2382 -1561  2551  1076  1257   764  8352  8574  3938  1354
  8582   968 -8105  5105  7635 -2535 -7609  7499  2164 -6747 -3606  6881
 -7744 -3303  -527 -2345 -6075  8087 -8798 -6299 -8755   625  2568 -3135
  7215  7405 -9082  7676  9230  5226 -6343  4399  3000   865 -5625  9298
  2340  8148   896 -5628  1204  2403  2945  2250  8284  5784  2697  4002
  9693 -3286  -183  9019 -8293  -435 -4574 -6008 -4303  6415  8412 -2697
 -7803  7574  3175 -5972 -5969 -2917 -1527 -8366]
sorted: 

array([ 9823,  9600,  9443,  9082,  8844,  8798,  8766,  8755,  8579,
        8560,  8366,  8293,  8105,  7803,  7744,  7689,  7609,  7606,
        7099,  7071,  6747,  6343,  6299,  6075,  6008,  5972,  5969,
        5661,  5628,  5625,  4871,  4574,  4481,  4333,  4303,  4107,
        4013,  3606,  3303,  3286,  3135,  2994,  2917,  2697,  2535,
        2345,  1872,  1646,  1561,  1527,  1067,  1019,  1012,   739,
         694,   527,   435,   183,   -85,  -625,  -764,  -865,  -896,
        -968, -1076, -1204, -1257, -1354, -2006, -2164, -2250, -2340,
       -2382, -2403, -2443, -2551, -2568, -2697, -2753, -2806, -2820,
       -2878, -2945, -3000, -3175, -3783, -3790, -3883, -3886, -3938,
       -3991, -4002, -4399, -4466, -4611, -5105, -5226, -5784, -6089,
       -6415, -6881, -7215, -7359, -7405, -7499, -7505, -7574, -7635,
       -7676, -8031, -8052, -8087, -8148, -8284, -8302, -8352, -8412,
       -8426, -8477, -8574, -8582, -8987, -9019, -9230, -9298, -9414,
       -9651, -9693]

1.3.6 Задание

Задача:
Создайте матрицу, выведите ее форму, размер и размерность.

In [ ]:
matrix = np.ones((5, 5, 5, 5), dtype=np.int32)
print("форма: ", matrix.shape, " размер: ", matrix.size, " размерность: ", matrix.ndim)

форма:  (5, 5, 5, 5)  размер:  625  размерность:  4


2.2.1 Пример

In [ ]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s1)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


2.2.2 Пример

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


2.2.3 Пример

In [ ]:
dataframe = pd.DataFrame()
dataframe["Name"] = ["Jackie Jackson", "Steven Stevenson"]
dataframe["Age"] = [38, 25]
dataframe["Is_Driver"] = [True, False]
dataframe

Name  Age  Is_Driver
0    Jackie Jackson   38       True
1  Steven Stevenson   25      False

2.2.4 Пример

In [ ]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

2.2.5 Пример

In [ ]:
dataframe.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [ ]:
dataframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [ ]:
dataframe.shape

(1313, 6)

In [ ]:
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

2.2.6 Пример

In [ ]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

2.2.7 Пример

In [ ]:
dataframe[dataframe["PClass"] == "1st"].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

2.3.1 Задание

Задача:
Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.


In [ ]:
a = pd.Series([1, 2, 3, 4, 5])
b = pd.Series([5, 4, 3, 2, 1])
distance1 = np.sqrt(np.sum((a - b) ** 2))
distance1

6.324555320336759

2.3.2 Задание

Задача:
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving MSFT.csv to MSFT.csv


In [ ]:
dataset_MSFT = pd.read_csv('MSFT.csv', sep=",", header=None)
dataset_MSFT

0           1           2           3           4           5  \
0          Date        Open        High         Low       Close   Adj Close   
1    2021-01-04  222.529999  223.000000  214.809998  217.690002  213.876358   
2    2021-01-05  217.259995  218.520004  215.699997  217.899994  214.082703   
3    2021-01-06  212.169998  216.490005  211.940002  212.250000  208.531662   
4    2021-01-07  214.039993  219.339996  213.710007  218.289993  214.465820   
..          ...         ...         ...         ...         ...         ...   
247  2021-12-23  332.750000  336.390015  332.730011  334.690002  331.583008   
248  2021-12-27  335.459991  342.480011  335.429993  342.450012  339.270966   
249  2021-12-28  343.149994  343.809998  340.320007  341.250000  338.082092   
250  2021-12-29  341.299988  344.299988  339.679993  341.950012  338.775635   
251  2021-12-30  341.910004  343.130005  338.820007  339.320007  336.170044   

            6  
0      Volume  
1    37130100  
2    23823000  
3    35930700  
4    27694500  
..        ...  
247  19617800  
248  19947000  
249  15661500  
250  15042000  
251  15994500  

[252 rows x 7 columns]

2.3.3 Задание

Задача:
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [ ]:
dataset_MSFT.columns = dataset_MSFT.iloc[0]
dataset_MSFT.drop(dataset_MSFT.index[0], inplace=True)

In [ ]:
dataset_MSFT.head()

0        Date        Open        High         Low       Close   Adj Close  \
1  2021-01-04  222.529999  223.000000  214.809998  217.690002  213.876358   
2  2021-01-05  217.259995  218.520004  215.699997  217.899994  214.082703   
3  2021-01-06  212.169998  216.490005  211.940002  212.250000  208.531662   
4  2021-01-07  214.039993  219.339996  213.710007  218.289993  214.465820   
5  2021-01-08  218.679993  220.580002  217.029999  219.619995  215.772568   

0    Volume  
1  37130100  
2  23823000  
3  35930700  
4  27694500  
5  22956200

In [ ]:
dataset_MSFT.tail()

0          Date        Open        High         Low       Close   Adj Close  \
247  2021-12-23  332.750000  336.390015  332.730011  334.690002  331.583008   
248  2021-12-27  335.459991  342.480011  335.429993  342.450012  339.270966   
249  2021-12-28  343.149994  343.809998  340.320007  341.250000  338.082092   
250  2021-12-29  341.299988  344.299988  339.679993  341.950012  338.775635   
251  2021-12-30  341.910004  343.130005  338.820007  339.320007  336.170044   

0      Volume  
247  19617800  
248  19947000  
249  15661500  
250  15042000  
251  15994500

In [ ]:
dataset_MSFT.shape

(251, 7)

In [ ]:
dataset_MSFT.describe()

0             Date        Open        High         Low       Close  \
count          251         251         251         251         251   
unique         251         247         247         247         250   
top     2021-01-04  278.029999  294.820007  247.509995  294.850006   
freq             1           2           2           2           2   

0        Adj Close    Volume  
count          251       251  
unique         250       251  
top     291.579468  37130100  
freq             2         1

In [ ]:
dataset_MSFT.iloc[1:4]

0        Date        Open        High         Low       Close   Adj Close  \
2  2021-01-05  217.259995  218.520004  215.699997  217.899994  214.082703   
3  2021-01-06  212.169998  216.490005  211.940002  212.250000  208.531662   
4  2021-01-07  214.039993  219.339996  213.710007  218.289993  214.465820   

0    Volume  
2  23823000  
3  35930700  
4  27694500

In [ ]:
dataset_MSFT[dataset_MSFT["Close"].astype('float') >= 215].head()

0        Date        Open        High         Low       Close   Adj Close  \
1  2021-01-04  222.529999  223.000000  214.809998  217.690002  213.876358   
2  2021-01-05  217.259995  218.520004  215.699997  217.899994  214.082703   
4  2021-01-07  214.039993  219.339996  213.710007  218.289993  214.465820   
5  2021-01-08  218.679993  220.580002  217.029999  219.619995  215.772568   
6  2021-01-11  218.470001  218.910004  216.729996  217.490005  213.679886   

0    Volume  
1  37130100  
2  23823000  
4  27694500  
5  22956200  
6  23031300

3.2.1 Пример

In [ ]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0,1))

scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

3.2.2 Пример

In [ ]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [ ]:
print("Mean:", round(standardized.mean()))
print("Standart deviation:", standardized.std())

Mean: 0
Standart deviation: 1.0


3.2.3 Пример

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
sclaer = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})

dfTest[["A", "B"]] = scaler.fit_transform(dfTest[["A", "B"]])
dfTest

A         B      C
0 -1.995290 -1.571117    big
1  0.436356 -0.603995  small
2  0.460289  0.100818    big
3  0.630058  0.985826  small
4  0.468586  1.088469  small

3.3.2 Задание

Задача:
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.


In [ ]:
from sklearn import preprocessing
dataset = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv", sep=",")

In [ ]:
scaler = preprocessing.MinMaxScaler()
dataset["sepal_length_cm"] = scaler.fit_transform(dataset["sepal_length_cm"].values.reshape(-1, 1))
mid = np.mean(dataset["sepal_width_cm"])
st_div = np.std(dataset["sepal_width_cm"])
dataset["sepal_width_cm"] = (dataset["sepal_width_cm"] - mid) / st_div
dataset.head()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa